
### example for Applied Energistics 2

64k:
  display: 64k ME Storage Component
  recipe:
    - [G,   E,   G]
    - [16k, Q, 16k]
    - [G,  16k,  G]
  result:
    - 64k: 1

16k:
  display: 16k ME Storage Component
  recipe:
    - [G,  E,  G]
    - [4k, Q, 4k]
    - [G,  4k, G]
  result:
    - 16k: 1

4k:
  display: 4k ME Storage Component
  recipe:
    - [R,  C,  R]
    - [1k, Q, 1k]
    - [R,  1k, R]
  result:
    - 4k: 1

1k:
  display: 1k ME Storage Component
  recipe:
    - [R,   PCQ,   R]
    - [PCQ,  L,  PCQ]
    - [R,   PCQ,   R]
  result:
    - 1k: 1

PCQ:
  display: Pure Certus Quartz Crystal
  recipe:
    - [CQS]
  result: 
    - PCQ: 1

CQS:
  display: Certus Quartz Seed
  recipe:
    - [Sand, CQD]
  result:
    - CQS: 2

CQD:
  display: Certus Quartz Dust
  recipe:
    - [CQ]
  result:
    - CQD: 1

CQ:
  display: Certus Quartz

Sand:
  display: Sand

L:
  display: Logic Processor
  recipe:
    - [PLC, R, PS]
  result:
    - L: 1

PLC:
  display: Printed Logic Circuit
  recipe:
    - [GI]
  result:
    - PLC: 1

GI:
  display: Gold Ingot

PS:
  display: Printed Silicon
  recipe:
    - [Silicon]
  result:
    - PS: 1

Silicon:
  display: Silicon
  recipe:
    - [CQD]
  result:
    - Silicon: 1

C:
  display: Calculation Processor
  recipe:
    - [PCC, R, PS]
  result:
    - C: 1

PCC:
  display: Printed Calculation Circuit
  recipe:
    - [PCQ]
  result:
    - PCC: 1

E:
  display: Engineering Processor
  recipe:
    - [PEC, R, PS]
  result:
    - E: 1

PEC:
  display: Printed Engineering Circuit
  recipe:
    - [Diamond]
  result:
    - PEC: 1

Diamond:
  display: Diamond

G:
  display: GlowStone Dust

Q:
  display: Quartz Glass
  recipe:
    - [CQD,  Glass,  CQD]
    - [Glass, CQD, Glass]
    - [CQD,  Glass,  CQD]
  result:
    - Q: 4

R:
  display: Redstone

Glass:
  display: Glass
  recipe:
    - [Sand]
  result:
    - Glass: 1

### example for RefinedStorage

Qartz Enritched Iron:
  display: Qartz Enritched Iron
  recipe:
    - [Iron Ingot,    Iron Ingot]
    - [Iron Ingot, Nether Quartz]
  result:
    - Qartz Enritched Iron: 4

Iron Ingot:
  display: Iron Ingot

Nether Quartz:
  display: Nether Quartz

Silicon(RS):
  display: Silicon(RS)
  recipe:
    - [Nether Quartz]
  result:
    - Silicon(RS): 1

Processor Binding:
  display: Processor Binding
  recipe:
    - [String, Slime ball, String]
  result:
    - Processor Binding: 8

String:
  display: String

Slime ball:
  display: Slime ball

Basic Processor:
  display: Basic Processor
  recipe:
    - [Raw Basic Processor]
  result:
    - Basic Processor: 1

Raw Basic Processor:
  display: Raw Basic Processor
  recipe:
    - [Processor Binding, Iron Ingot]
    - [Silicon(RS)      ,          R]
  result:
    - Raw Basic Processor: 1

Improved Processor:
  display: Improved Processor
  recipe:
    - [Raw Improved Processor]
  result:
    - Improved Processor: 1

Raw Improved Processor:
  display: Raw Improved Processor
  recipe:
    - [Processor Binding, GI]
    - [Silicon(RS)      ,  R]
  result:
    - Raw Improved Processor: 1

Advanced Processor:
  display: Advanced Processor
  recipe:
    - [Raw Advanced Processor]
  result:
    - Advanced Processor: 1

Raw Advanced Processor:
  display: Raw Advanced Processor
  recipe:
    - [Processor Binding, Diamond]
    - [Silicon(RS)      ,       R]
  result:
    - Raw Advanced Processor: 1

1k Storage Part:
  display: 1k Storage Part
  recipe:
    - [Silicon(RS) , Qartz Enritched Iron, Silicon(RS)]
    - [Glass,                  R,                Glass]
    - [Silicon(RS),          Glass,        Silicon(RS)]
  result:
    - 1k Storage Part: 1

4k Storage Part:
  display: 4k Storage Part
  recipe:
    - [Basic Processor, Qartz Enritched Iron, Basic Processor]
    - [1k Storage Part,          R,           1k Storage Part]
    - [Basic Processor,    1k Storage Part   ,Basic Processor]
  result:
    - 4k Storage Part: 1

16k Storage Part:
  display: 16k Storage Part
  recipe:
    - [Improved Processor, Qartz Enritched Iron, Improved Processor]
    - [4k Storage Part,             R,              4k Storage Part]
    - [Improved Processor,    4k Storage Part  , Improved Processor]
  result:
    - 16k Storage Part: 1

64k_Storage_Part:
  display: 64k Storage Part
  recipe:
    - [Advanced Processor, Qartz Enritched Iron, Advanced Processor]
    - [16k Storage Part,            R,             16k Storage Part]
    - [Advanced Processor,   16k Storage Part  , Advanced Processor]
  result:
    - 64k_Storage_Part: 1